<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_d1  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


// dashboatd snippets function
	function event_D1_snippet( &$header )
	{
		//echo 'owner ' . $_SESSION["email"] ;
//(Security::getUserData($email)) ;
//echo 'owner ' .(Security::getUserData($email)) ;
//echo '<br>owner '._SESSION["email"];
//echo '<br>owner '._SESSION["username"];

$nl = "<br>";

//echo $nl;
$userData = Security::currentUserData();
$my_user_email = $userData['email'] ;

//print_r($userData );
//echo $nl . $userData['email'] . $nl ; 
//$rs = DB::Select("total_approve_trans", "" );

$my_sql_1 = "select sum(coin) from credit_transactions where approved =  'yes' and owner_id= '" . $my_user_email ."'" ;
//echo $nl . $my_sql_1 ; // for debug

$rs = DB::Query($my_sql_1);
while( $record = $rs->fetchAssoc() ) {

echo $nl . ' You Have ' . $record["sum(coin)"] . ' coin' ;
$coin_total =  intval( $record["sum(coin)"] ) ;
//echo $nl . $coin_total ;

}

//---------------------------------------------------------------------------------------------------------------------------

$my_sql_2 = "select count(id) from placard where publish ='On' and owner_id='" . $my_user_email ."'" ;
// echo $nl . $my_sql_2 ; // for debug 

$rs = DB::Query($my_sql_2);
while( $record = $rs->fetchAssoc() ) {
echo $nl . 'you have place ' . $record["count(id)"] ." posts";
$placard_count = intval( $record["count(id)"] );
//echo $nl . $placard_count ; 
}



/// Calculate the result need .
$credit_left =  intval( $coin_total)  - intval( $placard_count ) ;
echo $nl ."You have " . $credit_left .' Credit left' ;

//if ( $credit_left < 1 ) {
//echo "please buy more coin // disable menu 3, 3.2";
//}

//if ( $credit_left < 1 ) 
//{
//  $title = $menuItem->getTitle();
//  if ($title=="3. ลงประกาศ กรอกฟอร์ม")
//    return false;
//}


return true;;
	}

}
?>
