<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_placard_admin  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		// $fileArray = 
$fileArray = json_decode($values["image1"],true);
$fileName ="prepare";
$fileName = $fileArray[0]["name"];
echo (" file name ".$fileName ."<br>") ;
$old_full_path_name = "/website/vnn.mac.in.th/lic/Design/images/". $fileName ;

$fileName ="prepare";
$values["image1_url"] = $fileName ;



//**********  Save new data in another table  ************

;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
