<?php
/**
 * Newspaper Class
 * Uses Puppeteer (Node.js) for PDF generation and PHP API for JSON data source.
 */

require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/database.php';

class Newspaper {
	private $db;

	public function __construct() {
		$this->db = Database::getInstance();
	}

	public function generateNewspaper($date, $adminId) {
		$date = $date ?: date('Y-m-d');

		$ads = $this->getApprovedAdvertisements($date);
		if (empty($ads)) {
			return ['success' => false, 'message' => 'ไม่มีประกาศที่อนุมัติสำหรับวันที่นี้'];
		}

		$newspaperId = $this->createOrResetNewspaperRecord($date, $adminId);
		if (!$newspaperId) {
			return ['success' => false, 'message' => 'ไม่สามารถสร้างรายการหนังสือพิมพ์ได้'];
		}

		$generatedFile = $this->generateWithPuppeteer($date, $newspaperId);
		if (!$generatedFile['success']) {
			return ['success' => false, 'message' => $generatedFile['message']];
		}

		$pageCount = $this->calculatePageCount(count($ads));
		$this->updateNewspaperRecord($newspaperId, $generatedFile['filename'], $pageCount, count($ads));
		$this->linkAdvertisementsToNewspaper($ads, $newspaperId, $date);

		logActivity("Generated newspaper {$newspaperId} using Puppeteer for {$date}");

		return [
			'success' => true,
			'message' => 'สร้างหนังสือพิมพ์สำเร็จ (Puppeteer)',
			'newspaper_id' => $newspaperId,
			'pdf_file' => $generatedFile['filename'],
			'page_count' => $pageCount,
			'ad_count' => count($ads)
		];
	}

	private function getApprovedAdvertisements($date) {
		$sql = "SELECT p.*
				FROM placard p
				WHERE p.status = 'approved'
				  AND DATE(COALESCE(p.placard_date, p.created_at)) = :date
				  AND p.id NOT IN (
					  SELECT placard_id
					  FROM newspaper_advertisements
					  WHERE placard_id IS NOT NULL
				  )
				ORDER BY p.approved_at ASC, p.id ASC";

		return $this->db->query($sql, [':date' => $date]);
	}

	private function createOrResetNewspaperRecord($date, $adminId) {
		$existing = $this->db->queryOne(
			"SELECT * FROM newspapers WHERE newspaper_date = :date LIMIT 1",
			[':date' => $date]
		);

		if ($existing) {
			$this->db->update(
				'newspapers',
				[
					'generated_by' => $adminId,
					'status' => 'draft',
					'pdf_file' => null,
					'page_count' => 0,
					'advertisement_count' => 0,
					'notes' => 'Regenerated at ' . date('Y-m-d H:i:s')
				],
				'id = :id',
				[':id' => $existing['id']]
			);

			$this->db->delete('newspaper_advertisements', 'newspaper_id = :id', [':id' => $existing['id']]);
			return (int)$existing['id'];
		}

		return $this->db->insert('newspapers', [
			'newspaper_date' => $date,
			'generated_by' => $adminId,
			'status' => 'draft',
			'notes' => 'Generated by Puppeteer',
			'generated_at' => date('Y-m-d H:i:s')
		]);
	}

	private function generateWithPuppeteer($date, $newspaperId) {
		$scriptPath = BASE_PATH . 'scripts/generate-newspaper-pdf.js';
		if (!file_exists($scriptPath)) {
			return ['success' => false, 'message' => 'ไม่พบไฟล์ Puppeteer script'];
		}

		$outputDir = BASE_PATH . 'public/newspapers/pdf/';
		if (!is_dir($outputDir) && !mkdir($outputDir, 0777, true) && !is_dir($outputDir)) {
			return ['success' => false, 'message' => 'ไม่สามารถสร้างโฟลเดอร์ PDF ได้'];
		}

		$filename = 'newspaper-' . $date . '-' . $newspaperId . '.pdf';
		$outputFile = $outputDir . $filename;

		$token = hash('sha256', DB_NAME . '|' . DB_USER . '|' . DB_HOST);
		$apiUrl = BASE_URL . 'api/newspaper-data.php?date=' . urlencode($date) . '&newspaper_id=' . urlencode((string)$newspaperId) . '&token=' . urlencode($token);

		$cmd = 'node '
			. escapeshellarg($scriptPath)
			. ' --api-url=' . escapeshellarg($apiUrl)
			. ' --output=' . escapeshellarg($outputFile)
			. ' --template=formal'
			. ' 2>&1';

		$result = shell_exec($cmd);

		if (!file_exists($outputFile) || filesize($outputFile) <= 0) {
			$message = 'Puppeteer สร้าง PDF ไม่สำเร็จ';
			if ($result) {
				$message .= ': ' . trim($result);
			}
			return ['success' => false, 'message' => $message];
		}

		return ['success' => true, 'filename' => $filename];
	}

	private function calculatePageCount($adCount) {
		if ($adCount <= 0) {
			return 0;
		}
		return (int)ceil($adCount / 4);
	}

	private function updateNewspaperRecord($id, $pdfFile, $pageCount, $adCount) {
		return $this->db->update(
			'newspapers',
			[
				'pdf_file' => $pdfFile,
				'page_count' => $pageCount,
				'advertisement_count' => $adCount,
				'generated_at' => date('Y-m-d H:i:s'),
				'status' => 'published'
			],
			'id = :id',
			[':id' => $id]
		);
	}

	private function linkAdvertisementsToNewspaper($ads, $newspaperId, $date) {
		foreach ($ads as $index => $ad) {
			$pageNumber = (int)floor($index / 4) + 1;

			$this->db->insert('newspaper_advertisements', [
				'placard_id' => $ad['id'],
				'newspaper_id' => $newspaperId,
				'newspaper_date' => $date,
				'page_number' => $pageNumber,
				'position' => 'middle',
				'type' => !empty($ad['pdf_file1']) ? 'pdf' : (!empty($ad['image1']) ? 'image' : 'template'),
				'status' => 'published',
				'credit_cost' => ($ad['ad_type'] === 'fullpage') ? CREDIT_PER_FULLPAGE_AD : CREDIT_PER_AD,
				'approved_by' => $ad['approved_by'] ?? null,
				'approved_at' => $ad['approved_at'] ?? null
			]);

			$this->db->update('placard', ['status' => 'published'], 'id = :id', [':id' => $ad['id']]);
		}
	}

	public function getAllNewspapers($page = 1, $limit = 20) {
		$offset = ($page - 1) * $limit;
		$sql = "SELECT * FROM newspapers ORDER BY newspaper_date DESC LIMIT :limit OFFSET :offset";
		$this->db->prepare($sql);
		$this->db->bind(':limit', $limit, PDO::PARAM_INT);
		$this->db->bind(':offset', $offset, PDO::PARAM_INT);
		return $this->db->fetchAll();
	}

	public function getApprovedAdCount($date = null) {
		$params = [];
		$whereDate = '';
		if (!empty($date)) {
			$whereDate = ' AND DATE(COALESCE(p.placard_date, p.created_at)) = :date';
			$params[':date'] = $date;
		}

		$sql = "SELECT COUNT(*) AS count
				FROM placard p
				WHERE p.status = 'approved'
				  {$whereDate}
				  AND p.id NOT IN (
					  SELECT placard_id FROM newspaper_advertisements WHERE placard_id IS NOT NULL
				  )";

		$result = $this->db->queryOne($sql, $params);
		return (int)($result['count'] ?? 0);
	}

	public function getById($id) {
		return $this->db->queryOne('SELECT * FROM newspapers WHERE id = :id LIMIT 1', [':id' => $id]);
	}

	public function getNewspaperById($id) {
		return $this->getById($id);
	}

	public function getAdvertisementsForNewspaper($newspaperId) {
		$sql = "SELECT p.* 
				FROM placard p
				INNER JOIN newspaper_advertisements na ON p.id = na.placard_id
				WHERE na.newspaper_id = :newspaper_id
				ORDER BY na.page_number ASC, p.id ASC";
		
		return $this->db->query($sql, [':newspaper_id' => $newspaperId]);
	}

	public function delete($id) {
		$row = $this->getById($id);
		if (!$row) {
			return ['success' => false, 'message' => 'ไม่พบหนังสือพิมพ์'];
		}

		if (!empty($row['pdf_file'])) {
			$path = BASE_PATH . 'public/newspapers/pdf/' . $row['pdf_file'];
			if (file_exists($path)) {
				@unlink($path);
			}
		}

		$this->db->query(
			'UPDATE placard SET status = :status WHERE id IN (SELECT placard_id FROM newspaper_advertisements WHERE newspaper_id = :id)',
			[':status' => 'approved', ':id' => $id]
		);

		$this->db->delete('newspaper_advertisements', 'newspaper_id = :id', [':id' => $id]);
		$this->db->delete('newspapers', 'id = :id', [':id' => $id]);

		return ['success' => true, 'message' => 'ลบหนังสือพิมพ์สำเร็จ'];
	}
}

